name: Criando pull request

on:
  pull_request:
    types: [opened, edited, deleted, reopened]
    branches:
      -'main'

jobs:
  job-pull-request:
    runs-on: ubuntu-latest
    steps:

      - name: Printa pull request
        run: echo "Um pull request foi aberto/editado/deletado/reaberto com destino na branch main"