name: Desafio01 - Workflow # Nome do Workflow

on:
  workflow_dispatch: #Executa o workflow manualmente
    inputs:
      docker_image:
        description: "Imagem criada no PICK 2024"
        type: string
        required: true #define o nome padrão
        default: "geforce8400gsd/giropops-senhas:1.0" #Imagem 

permissions: #permissoes de leitura do contaúdo e escrita para o sarif.
  contents: read
  actions: read
  security-events: write

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Validar input
        run: | #exibindo saida da imagem
          echo "docker_image='${{ inputs.docker_image }}'"
          if [ -z "${{ inputs.docker_image }}" ]; then
            echo "ERRO: input 'docker_image' está vazio."
            exit 1
          fi

      - name: Step 2 - Docker Pull # Baixando a imagem
        run: docker pull "${{ inputs.docker_image }}"

      - name: Step 2.1 - Listar imagem local # listando a imagem na VM
        run: docker image ls "${{ inputs.docker_image }}"

      # Login against a Docker registry except on PR 
      # https://github.com/docker/login-action https://github.com/docker/scout-action?tab=readme-ov-file
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Step 3 - Docker Scout - # analise de vulnerabilidades da imagem
        id: docker-scout-cves
        uses: docker/scout-action@v1
        with:
          command: cves #analisa as cves
          image: ${{ inputs.docker_image }} #imagem de input
          sarif-file: sarif.output.json #saída do json formatado para o sarif
          summary: true #log resumido

      - name: Step 3.1 - Envia para o Sarif scannear # https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
        id: upload-sarif #envia para o security code
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif.output.json
