name: Desafio01 - Workflow 

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: "Imagem criada no PICK 2024"
        required: true
        default: "geforce8400gsd/giropops-senhas:1.0"



jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Docker Pull
        run: docker pull "${{ inputs.docker_image }}"

      - name: Step 2 - visualizando imagem docker pullrizada
        run: docker image ls

