name: rigger deployment

on:
  deployment

jobs:
  job-deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Printa Deployment
        run: job triggado por um deployment externo