name: Testando  Trigger do tipo create

on:
  create

jobs:
  rint-branch-or-tag-creation:
    runs-on: ubuntu-latest
    steps:

      - name: Aviso sobre criação de branch ou tag
        run: echo "Uma nova tag ou branch foi criada no repositório"